### ISSUE TITLE
Upgrade to ocean.py v2.0.1

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/oceansimpleseller#30]
Update the fetch.ai integration to use the latest ocean.py release ([v2.0.1](https://pypi.org/project/ocean-lib/))

**Comment by LoznianuAnamaria** [comment]
Now that ocean.py 2.0.1 is available, let's upgrade the integration to the latest version.

**Comment by mariacarmina** [comment]
It is already integrated on `v4` branch. Closing this.
